#
# Rules for .github/workflows/labeler.yaml
#
platform:
  - changed-files:
      - any-glob-to-any-file: 'docs/platform/**'

service/clickhouse:
  - changed-files:
      - any-glob-to-any-file: 'docs/products/clickhouse/**'

service/dragonfly:
  - changed-files:
      - any-glob-to-any-file: 'docs/products/dragonfly/**'

service/flink:
  - changed-files:
      - any-glob-to-any-file: 'docs/products/flink/**'

service/kafka:
  - changed-files:
      - any-glob-to-any-file: 'docs/products/kafka/**'

service/kafka_connect:
  - changed-files:
      - any-glob-to-any-file: 'docs/products/kafka/kafka-connect/**'

service/kafka_mirrormaker:
  - changed-files:
      - any-glob-to-any-file: 'docs/products/kafka/kafka-mirrormaker/**'

service/mysql:
  - changed-files:
      - any-glob-to-any-file: 'docs/products/mysql/**'

service/pg:
  - changed-files:
      - any-glob-to-any-file: 'docs/products/postgresql/**'

tool/terraform:
  - changed-files:
      - any-glob-to-any-file: 'docs/tools/terraform/**'

tool/cli:
  - changed-files:
      - any-glob-to-any-file: 'docs/tools/cli/**'

tech:
  - changed-files:
      - any-glob-to-any-file: 'scripts/**'
      - any-glob-to-any-file: '.github/**'
      - any-glob-to-any-file: 'src/**'
      - any-glob-to-any-file: 'Dockerfile'
      - any-glob-to-any-file: 'docker-compose.yml'
