extends: existence
message: "Use '30 October 2026' format, not '%s'."
ignorecase: true
level: error
nonword: true
tokens:
  - '\\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\\s+\\d{1,2},?\\s+\\d{4}\\b'
  - '\\b\\d{1,2}(?:\\.|/|-)\\d{1,2}(?:\\.|/|-)\\d{2,4}\\b'
  - '\\b\\d{4}(?:\\.|/|-)\\d{1,2}(?:\\.|/|-)\\d{1,2}\\b'
  - '\\b\\d{1,2}\\s+(?:Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\\.?\\s+\\d{4}\\b'