extends: existence
message: "Do not judge complexity."
ignorecase: true
level: warning
tokens:
  - easily
  - quickly
  - merely
  - simply
  # - best
  - hardly
  - shortly
  - slowly
  - difficult
  - (?:make sure )?you understand
