extends: existence
message: "Do not judge complexity."
ignorecase: true
level: error
tokens:
  - easily
  - quickly
  - merely
  - simply
  - hardly
  - shortly
  - slowly
  - here
  - please
  - difficult
