extends: substitution
message: "Using '%s' instead of '%s'."
ignorecase: true
level: error
action:
  name: replace
swap:
  (?:if )?you want to: to
  (?:take |apply )?(?:the )?following steps: nothing
  and then: and
  check it out: see
  check out: see
  click (?:in|on): click
  navigate to: go to
  pre-requisites: prerequisites
  proceed as follows: nothing
  see a list: to list
  spin up: start
  view a list: list
  you need to: imperative
