name: PR labeler

on:
  - pull_request

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: '.github/workflow-config/labeling-rules.yaml'
          sync-labels: true
