name: Check for missing redirections

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_deleted_or_renamed_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for deleted or renamed files missing a redirection
      id: check_files
      run: |
        DELETED_FILES=$(git diff --name-status origin/main...HEAD | grep ^D | wc -l)
        RENAMED_FILES=$(git diff --name-status origin/main...HEAD | grep ^R | wc -l)
        REDIRECTS_MODIFIED=$(git diff --name-only origin/main...HEAD | grep ^_redirects | wc -l)
        echo "deleted_files=$DELETED_FILES" >> $GITHUB_ENV
        echo "renamed_files=$RENAMED_FILES" >> $GITHUB_ENV
        echo "redirects_modified=$REDIRECTS_MODIFIED" >> $GITHUB_ENV

    - name: Post comment on pull request
      if: (env.deleted_files != '0' || env.renamed_files != '0') && env.redirects_modified == '0'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "I see you have deleted or renamed a file, don't forget to add a redirection 😊"
          })
