name: Update parameters for all services

on:
  schedule:
    - cron: "0 6 * * 2"
  workflow_dispatch:

jobs:
  update-adv-params-cassandra:
    name: Update advanced parameters - Cassandra
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: cassandra

  update-adv-params-clickhouse:
    name: Update advanced parameters - Clickhouse
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: clickhouse

  update-adv-params-dragonfly:
    name: Update advanced parameters - Dragonfly
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: dragonfly

  update-adv-params-flink:
    name: Update advanced parameters - Flink
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: flink

  update-adv-params-grafana:
    name: Update advanced parameters - Grafana
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: grafana

  update-adv-params-influxdb:
    name: Update advanced parameters - Influxdb
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: influxdb

  update-adv-params-kafka_connect:
    name: Update advanced parameters - Kafka connect
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: kafka_connect

  update-adv-params-kafka_mirrormaker:
    name: Update advanced parameters - kafka_mirrormaker
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: kafka_mirrormaker

  update-adv-params-kafka:
    name: Update advanced parameters - kafka
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: kafka

  update-adv-params-m3aggregator:
    name: Update advanced parameters - m3aggregator
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: m3aggregator

  update-adv-params-m3db:
    name: Update advanced parameters - m3db
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: m3db

  update-adv-params-mysql:
    name: Update advanced parameters - mysql
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: mysql

  update-adv-params-opensearch:
    name: Update advanced parameters - opensearch
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: opensearch

  update-adv-params-redis:
    name: Update advanced parameters - redis
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: redis
