name: Update parameters for all services

on:
  schedule:
    - cron: '0 8 1,15 * *'
  workflow_dispatch:

jobs:
  update-adv-params-cassandra:
    name: Update parameters - Cassandra
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: cassandra

  update-adv-params-clickhouse:
    name: Update parameters - Clickhouse
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: clickhouse

  update-adv-params-dragonfly:
    name: Update parameters - Dragonfly
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: dragonfly

  update-adv-params-flink:
    name: Update parameters - Flink
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: flink

  update-adv-params-grafana:
    name: Update parameters - Grafana
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: grafana

  update-adv-params-kafka_connect:
    name: Update parameters - Kafka connect
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: kafka_connect

  update-adv-params-kafka_mirrormaker:
    name: Update parameters - Kafka_mirrormaker
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: kafka_mirrormaker

  update-adv-params-kafka:
    name: Update parameters - Kafka
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: kafka

  update-adv-params-m3aggregator:
    name: Update parameters - m3aggregator
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: m3aggregator

  update-adv-params-m3db:
    name: Update parameters - m3db
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: m3db

  update-adv-params-mysql:
    name: Update parameters - Mysql
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: mysql

  update-adv-params-opensearch:
    name: Update parameters - Opensearch
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: opensearch

  update-adv-params-redis:
    name: Update parameters - redis
    uses: ./.github/workflows/update-adv-params.yaml
    with:
      service-name: redis
